// Built-in idea library content shipped with the product.
let counter = 0;
const id = () => `idea_${++counter}_${Date.now()}`;

export function buildSeedIdeas() {
  counter = 0;
  return [
    {
      id: id(),
      title: '3 signs your child needs reading comprehension practice',
      category: 'Reading',
      suggested_platform: 'Facebook',
      suggested_content_type: 'Reel',
      hook: 'If your child can read the words but cannot explain the story, try this.',
      cta: 'Try Chalky this summer.',
      difficulty: 'Easy',
      estimated_time: '15 min',
      is_active: true,
      used_count: 0,
      sample_caption: 'Here are 3 signs your child might need extra help with reading comprehension:\n\n- They struggle to retell what they read\n- They guess words without understanding\n- They lose focus while reading\n\nSmall steps today lead to stronger readers tomorrow.\n\n#ReadingComprehension #ParentTips #Chalky #LearningAtHome #SmartContent',
      why_this_works: [
        'Addresses a common parent concern',
        'Provides quick, actionable insights',
        'High relatability and save potential',
        "Strong alignment with Chalky's value",
      ],
      assets: ['Example video (30s)', 'Infographic: 3 Signs', 'Blog link: Reading tips'],
      suggested_cta: "Try Chalky's reading practice to help your child build stronger comprehension skills!",
      recommended_audience: 'Parents with kids aged 6-12. Interests: education, parenting, reading tools, at-home learning',
      best_time_to_post: 'Weekdays: 7:00 PM - 9:00 PM. Weekends: 10:00 AM - 12:00 PM',
    },
    {
      id: id(),
      title: '5 quick comprehension tips for busy parents',
      category: 'Reading',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Story',
      hook: 'Small changes. Big impact.',
      cta: 'Get more 5-minute math drills inside Chalky.',
      difficulty: 'Easy',
      estimated_time: '10 min',
      is_active: true,
      used_count: 0,
      sample_caption: "5 quick comprehension tips you can use tonight:\n\n1. Ask 'what happened first?'\n2. Pause mid-page and predict what's next\n3. Have them retell it in their own words\n4. Point out new vocabulary together\n5. Celebrate progress, not perfection\n\n#ParentTips #ReadingComprehension #Chalky",
      why_this_works: [
        'Easy to scan on mobile',
        'Practical, no-prep tips busy parents can use tonight',
        'Sets up a natural next step toward the app',
      ],
      assets: ['Carousel template (5 slides)', 'Story sticker pack'],
      suggested_cta: 'Save this and try Chalky for daily reading practice.',
      recommended_audience: 'Parents with kids aged 5-10, busy schedules, homework-time stress.',
      best_time_to_post: 'Weekday mornings: 7:00 AM - 8:30 AM',
    },
    {
      id: id(),
      title: 'A 60-second math warm-up parents can do at the breakfast table',
      category: 'Math',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Reel',
      hook: 'You have 60 seconds before the bus comes — here is a math game that fits.',
      cta: 'Start a free Chalky summer plan.',
      difficulty: 'Easy',
      estimated_time: '20 min',
      is_active: true,
      used_count: 0,
      sample_caption: "One minute. One math game. Zero stress.\n\nTry this at breakfast tomorrow and tell me how it goes.\n\n#MathPractice #MorningRoutine #Chalky",
      why_this_works: [
        'Fits into an existing daily routine, low effort to try',
        'Demonstrates the product without feeling like an ad',
        'Strong hook for short-form video',
      ],
      assets: ['Example video (30s)', 'Printable warm-up card'],
      suggested_cta: 'Get more 5-minute math drills inside Chalky.',
      recommended_audience: 'Parents with kids aged 5-11, morning routine content viewers.',
      best_time_to_post: 'Weekday mornings: 6:30 AM - 8:00 AM',
    },
    {
      id: id(),
      title: 'How we keep learning going without "summer slide"',
      category: 'Summer learning',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Carousel',
      hook: 'Summer slide is real — here is what we do differently.',
      cta: 'Start a free Chalky summer plan.',
      difficulty: 'Medium',
      estimated_time: '30 min',
      is_active: true,
      used_count: 0,
      sample_caption: "Summer slide is real. Here's what actually works for us:\n\nSwipe through our 4-step summer learning routine, built around 15 minutes a day.\n\n#SummerLearning #SummerSlide #Chalky",
      why_this_works: [
        'Timely, seasonal relevance',
        'Carousel format encourages saves and shares',
        'Positions Chalky as the easy alternative to summer workbooks',
      ],
      assets: ['Carousel template (6 slides)', 'Blog link: Summer routine guide'],
      suggested_cta: 'Start your free Chalky summer plan today.',
      recommended_audience: 'Parents planning summer break activities, homeschool-curious families.',
      best_time_to_post: 'Weekends: 9:00 AM - 11:00 AM',
    },
    {
      id: id(),
      title: 'What a homeschool day actually looks like with Chalky',
      category: 'Homeschool',
      suggested_platform: 'YouTube',
      suggested_content_type: 'Video',
      hook: 'Everyone asks what our homeschool schedule looks like — full breakdown.',
      cta: 'See how Chalky fits into your homeschool routine.',
      difficulty: 'Advanced',
      estimated_time: '45 min',
      is_active: true,
      used_count: 0,
      sample_caption: "A full walkthrough of our homeschool day, including exactly when and how we use Chalky.\n\nTimestamps in the comments!\n\n#Homeschool #HomeschoolRoutine #Chalky",
      why_this_works: [
        'Long-form builds trust with homeschool community',
        'Shows real usage, not just claims',
        'Repurposes easily into shorts/reels',
      ],
      assets: ['Example video (8 min)', 'Printable daily schedule'],
      suggested_cta: 'See how Chalky fits into your homeschool routine.',
      recommended_audience: 'Homeschooling parents, homeschool co-ops, curriculum-curious families.',
      best_time_to_post: 'Sunday evenings: 6:00 PM - 8:00 PM',
    },
    {
      id: id(),
      title: '"I don\'t have time to sit and teach" — here is what I do instead',
      category: 'Parent pain points',
      suggested_platform: 'Facebook',
      suggested_content_type: 'Group post',
      hook: 'Busy parent confession: I cannot sit for 30 minutes of homework help every night.',
      cta: 'Chalky runs the practice so you do not have to.',
      difficulty: 'Easy',
      estimated_time: '10 min',
      is_active: true,
      used_count: 0,
      sample_caption: "Confession: I can't sit for 30 minutes of homework help every night. Here's what I do instead (and it actually works).\n\n#ParentLife #Chalky #BusyParents",
      why_this_works: [
        'Vulnerable, relatable opening builds trust in group settings',
        'Directly addresses the #1 objection: no time',
        'Feels like peer advice, not an ad',
      ],
      assets: ['Blog link: Busy parent routines'],
      suggested_cta: 'The app runs the practice so you do not have to.',
      recommended_audience: 'Parent Facebook groups, working parents, dual-income households.',
      best_time_to_post: 'Weeknights: 8:00 PM - 9:30 PM',
    },
    {
      id: id(),
      title: 'Real parent quote: "My kid asks to do Chalky now"',
      category: 'Testimonials',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Story',
      hook: 'Screenshot this message I got last week.',
      cta: 'Read more parent stories on our page.',
      difficulty: 'Easy',
      estimated_time: '10 min',
      is_active: true,
      used_count: 0,
      sample_caption: "This message made my week. Screenshots don't lie — kids actually asking to practice.\n\n#ParentTestimonial #Chalky #RealResults",
      why_this_works: [
        'Social proof from a real parent, low production effort',
        'Builds emotional trust before the ask',
        'Great for Stories, high completion rate',
      ],
      assets: ['Testimonial screenshot template'],
      suggested_cta: 'Read more parent stories on our page.',
      recommended_audience: 'Warm audience — existing followers, retargeting.',
      best_time_to_post: 'Weekday afternoons: 3:00 PM - 5:00 PM',
    },
    {
      id: id(),
      title: 'Quick screen-share: setting up a child profile in Chalky',
      category: 'Product demo',
      suggested_platform: 'TikTok',
      suggested_content_type: 'Video',
      hook: 'Setting up Chalky takes less time than making coffee.',
      cta: 'Link in bio to start your free trial.',
      difficulty: 'Medium',
      estimated_time: '25 min',
      is_active: true,
      used_count: 0,
      sample_caption: "Setting up Chalky takes less time than making your coffee. Screen recording, no cuts.\n\n#Chalky #ProductDemo #ParentTech",
      why_this_works: [
        'Removes the "is this complicated?" objection',
        'Screen-share format feels authentic and unscripted',
        'Short runtime fits TikTok/Reels native behavior',
      ],
      assets: ['Screen recording template', 'Example video (30s)'],
      suggested_cta: 'Link in bio to start your free trial.',
      recommended_audience: 'Cold audience, first-time viewers considering the app.',
      best_time_to_post: 'Weekday evenings: 7:00 PM - 9:00 PM',
    },
    {
      id: id(),
      title: 'Answering the #1 question I get: "Is this just another screen?"',
      category: 'FAQ',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Reel',
      hook: 'Is Chalky just another screen? I get asked this every week — here is my honest answer.',
      cta: 'DM me your questions, happy to help.',
      difficulty: 'Easy',
      estimated_time: '15 min',
      is_active: true,
      used_count: 0,
      sample_caption: "\"Is Chalky just another screen?\" I get this question every week. Here's my honest answer.\n\n#FAQ #ScreenTime #Chalky",
      why_this_works: [
        'Preemptively handles the top objection',
        'Honest tone builds credibility',
        'Encourages DMs, which warms up leads',
      ],
      assets: ['Example video (45s)'],
      suggested_cta: 'DM me your questions, happy to help.',
      recommended_audience: 'Parents concerned about screen time, skeptical first-time viewers.',
      best_time_to_post: 'Weekday evenings: 6:00 PM - 8:00 PM',
    },
    {
      id: id(),
      title: 'Chalky vs. a tutor: what actually fits a busy family',
      category: 'Comparison',
      suggested_platform: 'Blog',
      suggested_content_type: 'Blog post',
      hook: 'We priced out a tutor for a month and compared it to Chalky — here is what we found.',
      cta: 'See if Chalky is the right fit for your family.',
      difficulty: 'Advanced',
      estimated_time: '60 min',
      is_active: true,
      used_count: 0,
      sample_caption: "We priced out a private tutor for a month and compared it line by line to Chalky. Full breakdown on the blog (link in bio).\n\n#Chalky #TutoringCosts #ParentDecisions",
      why_this_works: [
        'Data-driven comparison builds trust with research-minded parents',
        'Long-form SEO content drives ongoing organic traffic',
        'Repurposes into carousel and short-form clips',
      ],
      assets: ['Blog link: Full comparison', 'Cost comparison graphic'],
      suggested_cta: 'See if Chalky is the right fit for your family.',
      recommended_audience: 'Parents currently paying for or considering a private tutor.',
      best_time_to_post: 'Any day, evergreen — share Tuesday-Thursday mornings for best reach.',
    },
    {
      id: id(),
      title: 'Why I started recommending Chalky to other parents',
      category: 'Personal story',
      suggested_platform: 'Facebook',
      suggested_content_type: 'Static post',
      hook: 'A year ago I was skeptical of "learning apps." Here is what changed my mind.',
      cta: 'Curious? I am happy to share my link.',
      difficulty: 'Medium',
      estimated_time: '25 min',
      is_active: true,
      used_count: 0,
      sample_caption: "A year ago I was skeptical of 'learning apps.' Here's what changed my mind about Chalky, in my own words.\n\n#Chalky #ParentStory #HonestReview",
      why_this_works: [
        'First-person narrative builds authenticity',
        'Works well for warm audiences already familiar with you',
        'Natural, low-pressure close',
      ],
      assets: ['Personal photo or family photo (optional)'],
      suggested_cta: 'Curious? I am happy to share my link.',
      recommended_audience: 'Existing friends/followers, warm local community groups.',
      best_time_to_post: 'Weekday evenings: 7:00 PM - 9:00 PM',
    },
    {
      id: id(),
      title: 'The 2-question check-in that tells you if your child is falling behind',
      category: 'Reading',
      suggested_platform: 'Pinterest',
      suggested_content_type: 'Static post',
      hook: 'Ask your child these two questions after they finish a book tonight.',
      cta: 'Save this and try Chalky for daily reading practice.',
      difficulty: 'Easy',
      estimated_time: '15 min',
      is_active: true,
      used_count: 0,
      sample_caption: "Ask these 2 questions tonight after reading time. Their answers tell you a lot.\n\n#ReadingTips #Chalky #ParentingHacks",
      why_this_works: [
        'Pinterest favors save-worthy, checklist-style content',
        'Simple enough to try the same night',
        'Long shelf life on Pinterest search',
      ],
      assets: ['Pin graphic template'],
      suggested_cta: 'Save this and try Chalky for daily reading practice.',
      recommended_audience: 'Parents searching Pinterest for reading tips and homeschool resources.',
      best_time_to_post: 'Evenings, any day: 8:00 PM - 10:00 PM',
    },
    {
      id: id(),
      title: 'Why math anxiety starts way earlier than you think',
      category: 'Math',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Carousel',
      hook: 'Math anxiety is not just a teenager thing — it starts as early as age 6.',
      cta: 'See how Chalky builds confidence, not just answers.',
      difficulty: 'Medium',
      estimated_time: '30 min',
      is_active: true,
      used_count: 0,
      sample_caption: "Math anxiety doesn't start in high school — it can start as early as age 6. Swipe for the early warning signs and what helps.\n\n#MathAnxiety #Chalky #ParentTips",
      why_this_works: [
        'Surprising stat earns the swipe/save',
        'Educates while positioning Chalky as the confidence-building solution',
        'Strong shareability among parent communities',
      ],
      assets: ['Carousel template (5 slides)', 'Blog link: Math anxiety guide'],
      suggested_cta: 'See how Chalky builds confidence, not just answers.',
      recommended_audience: 'Parents of kids aged 5-9, early elementary educators.',
      best_time_to_post: 'Weekday afternoons: 4:00 PM - 6:00 PM',
    },
    {
      id: id(),
      title: 'Email: 3 things to try before the school year starts',
      category: 'Summer learning',
      suggested_platform: 'Email',
      suggested_content_type: 'Email',
      hook: 'Three small habits now save a lot of stress in September.',
      cta: 'Start your free Chalky summer plan today.',
      difficulty: 'Medium',
      estimated_time: '30 min',
      is_active: true,
      used_count: 0,
      sample_caption: "Subject: 3 things to try before the first day of school\n\nThree small habits now save a lot of stress in September. Here's what we recommend starting this week.\n\n#Chalky #BackToSchool",
      why_this_works: [
        'Seasonal urgency drives opens and clicks',
        'Works well as a nurture email to existing leads',
        'Clear, scannable structure',
      ],
      assets: ['Email template', 'Blog link: Back-to-school checklist'],
      suggested_cta: 'Start your free Chalky summer plan today.',
      recommended_audience: 'Email subscribers, warm leads from past trials.',
      best_time_to_post: 'Send Tuesday or Wednesday: 9:00 AM - 10:00 AM',
    },
  ];
}
