// Built-in idea library content shipped with the product.
// These are starter prompts for affiliates, not user/demo data.
let counter = 0;
const id = () => `idea_${++counter}_${Date.now()}`;

export function buildSeedIdeas() {
  counter = 0;
  return [
    {
      id: id(),
      title: '3 signs your child needs reading comprehension practice',
      category: 'Reading',
      suggested_platform: 'Facebook',
      suggested_content_type: 'Reel',
      hook: 'If your child can read the words but cannot explain the story, try this.',
      cta: 'Try it this summer.',
      difficulty: 'Easy',
      estimated_time: '15 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'A 60-second math warm-up parents can do at the breakfast table',
      category: 'Math',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Reel',
      hook: 'You have 60 seconds before the bus comes — here is a math game that fits.',
      cta: 'Get more 5-minute math drills inside the app.',
      difficulty: 'Easy',
      estimated_time: '20 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'How we keep learning going without "summer slide"',
      category: 'Summer learning',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Carousel',
      hook: 'Summer slide is real — here is what we do differently.',
      cta: 'Start a free summer learning plan.',
      difficulty: 'Medium',
      estimated_time: '30 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'What a homeschool day actually looks like with us',
      category: 'Homeschool',
      suggested_platform: 'YouTube',
      suggested_content_type: 'Video',
      hook: 'Everyone asks what our homeschool schedule looks like — full breakdown.',
      cta: 'See how it fits into your homeschool routine.',
      difficulty: 'Advanced',
      estimated_time: '45 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: '"I don\'t have time to sit and teach" — here is what I do instead',
      category: 'Parent pain points',
      suggested_platform: 'Facebook',
      suggested_content_type: 'Group post',
      hook: 'Busy parent confession: I cannot sit for 30 minutes of homework help every night.',
      cta: 'The app runs the practice so you do not have to.',
      difficulty: 'Easy',
      estimated_time: '10 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Real parent quote: "My kid asks to do this now"',
      category: 'Testimonials',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Story',
      hook: 'Screenshot this message I got last week.',
      cta: 'Read more parent stories on our page.',
      difficulty: 'Easy',
      estimated_time: '10 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Quick screen-share: setting up a child profile',
      category: 'Product demo',
      suggested_platform: 'TikTok',
      suggested_content_type: 'Video',
      hook: 'Setting up takes less time than making coffee.',
      cta: 'Link in bio to start your free trial.',
      difficulty: 'Medium',
      estimated_time: '25 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Answering the #1 question I get: "Is this just another screen?"',
      category: 'FAQ',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Reel',
      hook: 'Is this just another screen? I get asked this every week — here is my honest answer.',
      cta: 'DM me your questions, happy to help.',
      difficulty: 'Easy',
      estimated_time: '15 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Us vs. a tutor: what actually fits a busy family',
      category: 'Comparison',
      suggested_platform: 'Blog',
      suggested_content_type: 'Blog post',
      hook: 'We priced out a tutor for a month and compared it to our program — here is what we found.',
      cta: 'See if it is the right fit for your family.',
      difficulty: 'Advanced',
      estimated_time: '60 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Why I started recommending this to other parents',
      category: 'Personal story',
      suggested_platform: 'Facebook',
      suggested_content_type: 'Static post',
      hook: 'A year ago I was skeptical of "learning apps." Here is what changed my mind.',
      cta: 'Curious? I am happy to share my link.',
      difficulty: 'Medium',
      estimated_time: '25 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'The 2-question check-in that tells you if your child is falling behind',
      category: 'Reading',
      suggested_platform: 'Pinterest',
      suggested_content_type: 'Static post',
      hook: 'Ask your child these two questions after they finish a book tonight.',
      cta: 'Save this and try it for daily reading practice.',
      difficulty: 'Easy',
      estimated_time: '15 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Why math anxiety starts way earlier than you think',
      category: 'Math',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Carousel',
      hook: 'Math anxiety is not just a teenager thing — it starts as early as age 6.',
      cta: 'See how it builds confidence, not just answers.',
      difficulty: 'Medium',
      estimated_time: '30 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Answering parent comments live',
      category: 'FAQ',
      suggested_platform: 'Instagram',
      suggested_content_type: 'Live',
      hook: 'Drop your homework-time struggles in the comments — answering live tonight.',
      cta: 'Try the tip that fits your family this week.',
      difficulty: 'Advanced',
      estimated_time: '40 min',
      is_active: true,
      used_count: 0,
    },
    {
      id: id(),
      title: 'Email: 3 things to try before the school year starts',
      category: 'Summer learning',
      suggested_platform: 'Email',
      suggested_content_type: 'Email',
      hook: 'Three small habits now save a lot of stress in September.',
      cta: 'Start your free summer plan today.',
      difficulty: 'Medium',
      estimated_time: '30 min',
      is_active: true,
      used_count: 0,
    },
  ];
}
